apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cve-intelligence-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: cve-intelligence
