apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  GROQ_API_KEY: {{ .Values.GROQ_API_KEY | b64enc }}
  PINECONE_API_KEY: {{ .Values.PINECONE_API_KEY | b64enc }}
  PINECONE_ENVIRONMENT: {{ .Values.PINECONE_ENVIRONMENT | b64enc }}
  PINECONE_INDEX_NAME: {{ .Values.PINECONE_INDEX_NAME | b64enc }}
  PINECONE_HOST: {{ .Values.PINECONE_HOST | b64enc }}
  SENTENCE_TRANSFORMER_MODEL: {{ .Values.SENTENCE_TRANSFORMER_MODEL | b64enc }}
  LLM_MODEL: {{ .Values.LLM_MODEL | b64enc }}
  LLM_TEMPERATURE: {{ .Values.LLM_TEMPERATURE | toString | b64enc }}
  K_NEIGHBORS: {{ .Values.K_NEIGHBORS | toString | b64enc }}
  FINAL_K: {{ .Values.FINAL_K | toString | b64enc }}
