apiVersion: v1
kind: Service
metadata:
  name: {{ include "cve-intelligence.fullname" . }}-light
  labels:
    {{- include "cve-intelligence.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      name: http
  selector:
    app: {{ .Release.Name }}-light